name: Deploy DmailBot

on:
  push:
    branches:
      - main  # 또는 배포에 사용하는 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: ./mvnw clean package -DskipTests
        working-directory: DmailBot

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: DmailBot/target/DmailBot-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/

      - name: Restart application
        uses: appleboy/ssh-action@v1.0.3
        # continue-on-error: true
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # pkill -f DmailBot || true
            echo "Starting DmailBot..." >> /home/ubuntu/app.log
            java -jar /home/ubuntu/DmailBot-0.0.1-SNAPSHOT.jar > /home/ubuntu/app.log 2>&1
